version: '3'

services:
  postgresql:
    image: postgres
    container_name: pg-base
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: